Models/ErrorViewModel.cs
namespace Mvc101.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Mvc101.Controllers
{
    public class FilesController : Controller
    {
        // GET: Files
        public ActionResult Index()
        {
            string[] files = Directory.GetFiles("TextFiles");
            return View(files);
        }

        // GET: Files/Details/5
        public IActionResult Details(string id)
        {
            string[] files = Directory.GetFiles("TextFiles");
            string? filePath = Array.Find(files, s => s.Contains(id));
            string? fileContent = System.IO.File.ReadAllText(filePath!);
            ViewBag.fileContent = fileContent;
            return View();
        }

        // GET: Files/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Files/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Files/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Files/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Files/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Files/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Mvc101.Models;


namespace Mvc101.Controllers;
// name of the controller
// two methods
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        string[] days = {"Mon","Tue"};
        ViewData["days"] = days;
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
    public IActionResult Bogus()
    {
        // ViewData and ViewBag are p much the same thing, interchangeable
        // ViewBag.Date == ViewData["Date"]
        ViewData["Name"] = "Home Page\n\n";
        ViewBag.Date = DateTime.Now;

        // we can pass only one argument to the View class.
        // if we wana pass multiple items, create a class that contains all the data 
        // you want
        string[] days = {"Mon","Tue"};
        return View(days);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProcesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Mvc101.Controllers
{
    public class ProcesController : Controller
    {
        // GET: Proces
        public ActionResult Index()
        {
            // Process[] procs = Process.GetProcesses();
            return View(Process.GetProcesses());
        }

        public IActionResult Display(int id) {
    Process osProcess = Process.GetProcessById(id);
    return View(osProcess);
}



        // GET: Proces/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Proces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proces/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Proces/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Proces/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Proces/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Proces/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Files/Details.cshtml
@{
    ViewData["Title"] = "File Content Page";
    string content = ViewBag.fileContent as string;
}

<div class="text-center">
    @content

    <table>
        @* <tr>
            <td>ID</td>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <td>Count</td>
            <td>@Model.Count</td>
        </tr> *@
        <tr>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>

Views/Files/Index.cshtml
@Model
@using System
@{
    ViewData["Title"] = "Files";
}

<div class="text-center">
    <h1 class="display-4">Welcome to COMP4870.</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <ul>
    @foreach (var item in Model)
    {
        
        <li><a asp-controller="Files"
        asp-action="Details"
        asp-route-id="@System.IO.Path.GetFileName(@item)">@System.IO.Path.GetFileName(@item)</a></li>
    }
    </ul>
</div>

Views/Home/Bogus.cshtml
@model string[]
@{
    // the above line is parsing the concrete class passed to this view

    // ViewData["sth"] is a dictionary data entry, which you can use
    // across different related files
    ViewData["Title"] = "Bogus";
    var date = (System.DateTime) ViewBag.Date;
    var date1 = (System.DateTime) ViewData["Date"]!;
}

<h1>@ViewData["Title"]</h1>

<div>
    THis is my first .NET page.@ViewData["Name"]
    The current time is @ViewBag.Date .
    @date.ToShortDateString()
</div>

Views/Home/Index.cshtml
@{
    // here you can type in C#
    ViewData["Title"] = "Home Page";
    string[] days = ViewData["days"] as string[];
}

<div class="text-center">
    <h1 class="display-4">Welcome to COMP4870.</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    @* <ul>
        @foreach (var item in days)
        {
         <li>@item</li>   
        }
    </ul> *@
    <ol>
        <li>A01280625</li>
        <li>Yoshiyuki Nagai</li>
        <li>Language agnostic full-stack, frontend, backend web developer</li>
    </ol>
</div>

Views/Proces/Display.cshtml
@using System.Diagnostics
@model System.Diagnostics.Process[]
@{
    // here you can type in C#
    ViewData["Title"] = "Home Page";
    @* var procs = ViewBag.Procs as Process[]; *@

}

<div class="text-center">
    <table>
        @* <tr>
            <td>ID</td>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <td>Count</td>
            <td>@Model.Count</td>
        </tr> *@
        <tr>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>

Views/Proces/Index.cshtml
@using System.Diagnostics
@model System.Diagnostics.Process[]
@{
    // here you can type in C#
    ViewData["Title"] = "Home Page";
    @* var procs = ViewBag.Procs as Process[]; *@

}

<div class="text-center">
    <h1 class="display-4">Welcome to Proces</h1>
<ul>
@foreach (var item in Model)
{
    <li><a asp-controller="Process"
    asp-action="Display"
    asp-route-id="@item.Id">@item.ProcessName</a></li>
}
</ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc101</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc101.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc101</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Bogus">Bogus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proces" asp-action="Index">Proces</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Index">Files</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mvc101 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>